---
name: Galaxy

on:
  pull_request:
    types: [closed]
    branch:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v2

      - name: install ansible
        run: apt install ansible

      - name: authenticate to ansibe galaxy
        run: ansible-galaxy login --github-token ${{ secrets.GITHUB_TOKEN }}

      - name: build galaxy collections
        run: ansible-galaxy collection build

      - name: publish galaxy collections
        run: ansible-galaxy collection publish ./marmorag-ansodium-*
